export const organogramData = {
  title: "Air Officer Commanding (AOC)",
  children: [
    {
      title: "Chief of Staff (COS)",
      children: [
        { title: "Command Training Officer" },
        { title: "Command Administrative Officer" },
        { title: "Command Evaluation Officer" },
        { title: "Command Aircraft Engineering Officer" },
        { title: "Command Communications & IS Officer" },
        { title: "Command Logistics Officer" },
        { title: "Command Medical Officer" },
        { title: "Command Finance Officer" },
        { title: "Command Air Provost Officer" },
        { title: "Command Education Officer" },
        { title: "Command Legal Officer" },
        { title: "Command Intelligence Officer" },
        { title: "Command Public Relations Officer" },
        { title: "Command Sports Officer" },
      ],
    },
    {
      title: "Units",
      children: [
        { title: "401 Flying Training School" },
        { title: "Air Traffic Services Training Centre" },
        { title: "413 Force Protection Group" },
        { title: "431 Engineering Group" },
        { title: "441 Communications Group" },
        { title: "453 Base Services Group" },
        { title: "461 NAF Hospital" },
        { title: "Central Avionics Overhaul & Calibration Centre" },
        { title: "Air Force Comprehensive School, Kaduna" },
        { title: "403 Flying Training School, Kano" },
        { title: "455 Base Services Group, Kano" },
        { title: "465 NAF Hospital, Kano" },
        { title: "Air Force Comprehensive School, Kano" },
        { title: "405 Helicopter Combat Training Group, Enugu" },
        { title: "409 International Helicopter Flying School, Enugu" },
        { title: "410 Central Flying School, Katsina" },
        { title: "407 Air Combat Training Group, Kainji" },
        { title: "NAF School of Air Intelligence, Makurdi" },
        { title: "Air Force Girls Comprehensive School, Abuja" },
        { title: "NAF Institute of Safety, Ikpetu-Ijesha" },
      ],
    },
  ],
};
